"""empty message

Revision ID: 08c51047699f
Revises: 6776cc50ac6b
Create Date: 2023-07-31 10:12:03.560936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c51047699f'
down_revision = '6776cc50ac6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
