"""empty message

Revision ID: 6776cc50ac6b
Revises: b23ffc8e7183
Create Date: 2023-07-31 09:04:10.866741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6776cc50ac6b'
down_revision = 'b23ffc8e7183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('population',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
